name: Install build prerequisites

inputs:
  os:
    description: The operating system (runner type) being used, e.g. `ubuntu-latest`
    required: true
  crypto:
    description: The crypto library being used
    required: true
  cache-dir:
    description: Where to put vcpkg cache
    required: true

runs:
  using: "composite"
  steps:
    - name: Set VCPKG_BINARY_SOURCES
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache-dir }}
      run: |
        # While cibuildwheel on Windows/macOS builds directly on the host,
        # it uses containers on Linux, so we need to fix the vcpkg cache directory.
        # The host filesystem is mounted as `/host` in these containers, so we simply prepend that to the path.
        # See https://cibuildwheel.pypa.io/en/stable/platforms/#linux-containers.
        # TODO: cibw also copies the entire project directory, *including* the cache, since we're currently putting it in the workspace. We should look into placing it outside the workspace to avoid the unnecessary copy.
        if [ "${{ runner.os }}" = "Linux" ]; then
          CACHE_DIR="/host${CACHE_DIR}"
        fi
        echo "VCPKG_BINARY_SOURCES=clear;files,$CACHE_DIR,readwrite" >> "$GITHUB_ENV"

    - name: Capture vcpkg revision for use in cache key
      shell: bash
      id: vcpkg-ref
      run: |
        echo "ref=$(git -C libdave/cpp/vcpkg rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-dir }}
        key: v0-vcpkg-${{ inputs.os }}-${{ inputs.crypto }}-${{ steps.vcpkg-ref.outputs.ref }}-${{ hashFiles(format('libdave/cpp/vcpkg-alts/{0}/*', inputs.crypto)) }}
        restore-keys: |
          v0-vcpkg-${{ inputs.os }}-${{ inputs.crypto }}-${{ steps.vcpkg-ref.outputs.ref }}-
          v0-vcpkg-${{ inputs.os }}-${{ inputs.crypto }}-

    - name: Run vcpkg bootstrap
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          libdave/cpp/vcpkg/bootstrap-vcpkg.bat
        else
          ./libdave/cpp/vcpkg/bootstrap-vcpkg.sh
        fi

    # NOTE: we don't currently build with boringssl, so this is no longer needed but retained here for future reference.
    # # Some versions of clang++ on macOS appear to always insert /usr/local/include at the start of the include paths,
    # # notably disregarding -isystem. This breaks building with boringssl, since the includes end up conflicting.
    # # Thanks Apple.
    # # https://github.com/orgs/Homebrew/discussions/5642
    # # https://stackoverflow.com/a/66377265
    # - name: Unlink openssl headers on macOS
    #   shell: bash
    #   if: runner.os == 'macOS' && inputs.crypto == 'boringssl'
    #   run: |
    #     brew unlink openssl@3
