name: Install build prerequisites

inputs:
  os-arch-key:
    description: The runner OS, target arch, and libc implementation used for the cache key, e.g. `ubuntu-latest-riscv64-musl`
    required: true
  crypto:
    description: The crypto library being used
    required: true
  cache-dir:
    description: Where to put vcpkg cache
    required: true

runs:
  using: "composite"
  steps:
    - name: Set VCPKG_BINARY_SOURCES
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache-dir }}
      run: |
        # While cibuildwheel on Windows/macOS builds directly on the host,
        # it uses containers on Linux, so we need to fix the vcpkg cache directory.
        # The host filesystem is mounted as `/host` in these containers, so we simply prepend that to the path.
        # See https://cibuildwheel.pypa.io/en/stable/platforms/#linux-containers.
        # TODO: cibw also copies the entire project directory, *including* the cache, since we're currently putting it in the workspace. We should look into placing it outside the workspace to avoid the unnecessary copy.
        if [ "${{ runner.os }}" = "Linux" ]; then
          CACHE_DIR="/host${CACHE_DIR}"
        fi
        echo "VCPKG_BINARY_SOURCES=clear;files,$CACHE_DIR,readwrite" >> "$GITHUB_ENV"

    - name: Capture vcpkg revision for use in cache key
      shell: bash
      id: vcpkg-ref
      run: |
        echo "ref=$(git -C libdave/cpp/vcpkg rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-dir }}
        key: vcpkg-deps--${{ inputs.os-arch-key }}--${{ inputs.crypto }}-${{ steps.vcpkg-ref.outputs.ref }}-${{ hashFiles(format('libdave/cpp/vcpkg-alts/{0}/**', inputs.crypto)) }}
        restore-keys: |
          vcpkg-deps--${{ inputs.os-arch-key }}--${{ inputs.crypto }}-${{ steps.vcpkg-ref.outputs.ref }}-
          vcpkg-deps--${{ inputs.os-arch-key }}--${{ inputs.crypto }}-

    - name: Run vcpkg bootstrap
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          libdave/cpp/vcpkg/bootstrap-vcpkg.bat -disableMetrics
        elif [ "${{ runner.os }}" = "macOS" ]; then
          ./libdave/cpp/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        fi
        # linux will bootstrap later, since it runs in a separate container instead of directly on the host

    - name: Restore cached vcpkg-tool binary
      if: runner.os == 'Linux'
      uses: actions/cache@v4
      with:
        path: libdave/cpp/vcpkg/vcpkg
        key: vcpkg-tool--${{ inputs.os-arch-key }}--${{ steps.vcpkg-ref.outputs.ref }}
        # no restore keys, so that we rebuild when the submodule was updated

    # This ensures the (potentially locally built) vcpkg binary gets copied to
    # the path expected by the previous cache step.
    # Note that we use `/host` again, since this will be used from inside the container.
    - name: Set $COPY_VCPKG_BINARY_PATH
      if: runner.os == 'Linux'
      shell: bash
      run: |
        VCPKG_PATH="$PWD/libdave/cpp/vcpkg/vcpkg"
        echo "COPY_VCPKG_BINARY_PATH=/host${VCPKG_PATH}" >> $GITHUB_ENV

    # This is awful and certainly not the intended way of doing things,
    # but it works for CI purposes.
    # Especially on emulated architectures, this reduces initial build time by ~1h.
    - name: Only create `Release` builds of dependencies
      shell: bash
      working-directory: libdave/cpp/vcpkg
      run: |
        for f in $(find ./triplets -name '*.cmake'); do
          echo "set(VCPKG_BUILD_TYPE release)" >> "$f"
          git update-index --assume-unchanged "$f"
        done

    # NOTE: we don't currently build with boringssl, so this is no longer needed but retained here for future reference.
    # # Some versions of clang++ on macOS appear to always insert /usr/local/include at the start of the include paths,
    # # notably disregarding -isystem. This breaks building with boringssl, since the includes end up conflicting.
    # # Thanks Apple.
    # # https://github.com/orgs/Homebrew/discussions/5642
    # # https://stackoverflow.com/a/66377265
    # - name: Unlink openssl headers on macOS
    #   shell: bash
    #   if: runner.os == 'macOS' && inputs.crypto == 'boringssl'
    #   run: |
    #     brew unlink openssl@3
